/**
 * Devran AI Kit — Universal Slash Command Bridge Generator
 *
 * Generates IDE-specific bridge files that map each IDE's native
 * slash command system to .agent/workflows/*.md source-of-truth files.
 *
 * Supported IDEs:
 *   - Claude Code / Antigravity (.claude/commands/)
 *   - Cursor (.cursor/commands/)
 *   - OpenCode (.opencode/commands/)
 *   - VS Code Copilot (.github/prompts/)
 *   - Windsurf (.windsurf/workflows/)
 *
 * Security hardening:
 *   - S1: Strict name validation (path traversal + Windows reserved names)
 *   - S2: YAML injection prevention (sanitizeForYaml)
 *   - S3: Markdown link injection prevention (sanitizeForMarkdown)
 *   - S4: Provenance header for safe overwrite (isKitGeneratedFile)
 *   - S5: Workflow file path traversal prevention
 *   - S6: Manifest items DoS cap
 *   - S8: File size limit before read
 *   - S9: Regex field name escaping
 *
 * @module lib/command-bridge
 * @since v5.2.0
 */

'use strict';

const fs = require('fs');
const path = require('path');

const {
  CLAUDE_DIR,
  CLAUDE_COMMANDS_DIR,
  CURSOR_DIR,
  CURSOR_COMMANDS_DIR,
  OPENCODE_DIR,
  OPENCODE_COMMANDS_DIR,
  GITHUB_PROMPTS_DIR,
  WINDSURF_DIR,
  WINDSURF_WORKFLOWS_DIR,
  MAX_WORKFLOW_ITEMS,
  MAX_WORKFLOW_FILE_SIZE,
  SAFE_COMMAND_NAME,
  KIT_BRIDGE_HEADER,
} = require('./constants');

const VERSION = require('../package.json').version;

/**
 * Provenance header embedded in every Kit-generated bridge file.
 * Used by isKitGeneratedFile() to distinguish Kit bridges from user commands.
 */
const BRIDGE_HEADER = `${KIT_BRIDGE_HEADER} v${VERSION} -->`;

// ---------------------------------------------------------------------------
// Core utility functions
// ---------------------------------------------------------------------------

/**
 * Extracts a single field value from YAML frontmatter content.
 * Regex-safe: escapes field name before constructing RegExp (S9).
 *
 * @param {string} content - Full file content with frontmatter
 * @param {string} field - Field name to extract (e.g., 'description')
 * @returns {string|null} Extracted value or null
 */
function extractFrontmatterField(content, field) {
  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fmMatch) return null;

  const escaped = field.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const fieldMatch = fmMatch[1].match(new RegExp(`^${escaped}:\\s*(.+)$`, 'm'));
  if (!fieldMatch) return null;

  return fieldMatch[1].trim().replace(/\r$/, '').replace(/^["']|["']$/g, '');
}

/**
 * Sanitizes a description for safe embedding in YAML frontmatter (S2).
 * Strips newlines, escapes double quotes, limits length.
 *
 * @param {string} raw - Raw description string
 * @returns {string} YAML-safe single-line description
 */
function sanitizeForYaml(raw) {
  if (typeof raw !== 'string') return '';
  return raw.split(/\r?\n/)[0].trim().replace(/\\/g, '\\\\').replace(/"/g, '\\"').substring(0, 200);
}

/**
 * Sanitizes a description for safe embedding in plain markdown (S3).
 * Strips markdown links, bare URLs, collapses whitespace, limits length.
 *
 * @param {string} raw - Raw description string
 * @returns {string} Markdown-safe plain text description
 */
function sanitizeForMarkdown(raw) {
  if (typeof raw !== 'string') return '';
  return raw
    .split(/\r?\n/)[0]
    .trim()
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/https?:\/\/\S+/g, '')
    .replace(/\s{2,}/g, ' ')
    .substring(0, 200);
}

/**
 * Validates that a workflow file path resolves within the agent directory (S5).
 *
 * @param {string} agentDir - Absolute path to .agent/ directory
 * @param {string} relativeFile - Relative file path from manifest
 * @returns {string|null} Resolved absolute path, or null if traversal detected
 */
function safeResolveWorkflowPath(agentDir, relativeFile) {
  if (typeof relativeFile !== 'string' || relativeFile.includes('\0')) return null;
  const resolved = path.resolve(agentDir, relativeFile);
  const boundary = path.resolve(agentDir) + path.sep;
  if (!resolved.startsWith(boundary)) return null;
  return resolved;
}

/**
 * Checks if a file was generated by Devran AI Kit (S4).
 * Reads the first 128 bytes and checks for the provenance header.
 *
 * @param {string} filePath - Absolute path to the file
 * @returns {boolean} True if the file contains the Kit bridge header
 */
function isKitGeneratedFile(filePath) {
  try {
    const fd = fs.openSync(filePath, 'r');
    try {
      const buf = Buffer.alloc(128);
      fs.readSync(fd, buf, 0, 128, 0);
      return buf.toString('utf-8').includes(KIT_BRIDGE_HEADER);
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return false;
  }
}

/**
 * Detects which IDEs are present in the project directory.
 * Claude Code is always included as Kit's primary ecosystem — even if
 * `.claude/` does not yet exist, because `kit init` creates `.claude/commands/`.
 * VS Code requires explicit opt-in via `--ide vscode` (audit finding A2).
 *
 * @param {string} projectRoot - Absolute path to project root
 * @returns {string[]} Array of IDE identifiers
 */
function detectIDEs(projectRoot) {
  // Claude is always generated — Kit's primary ecosystem. The .claude/commands/
  // directory is created by Kit init, so it may not exist yet on first run.
  const detected = ['claude'];
  if (fs.existsSync(path.join(projectRoot, '.cursor'))) detected.push('cursor');
  if (fs.existsSync(path.join(projectRoot, '.opencode'))) detected.push('opencode');
  if (fs.existsSync(path.join(projectRoot, '.windsurf'))) detected.push('windsurf');
  return detected;
}

// ---------------------------------------------------------------------------
// Shared workflow resolution
// ---------------------------------------------------------------------------

/**
 * Resolves workflows from manifest with all security validations applied.
 *
 * @param {string} agentDir - Absolute path to .agent/ directory
 * @param {object} manifest - Parsed manifest.json
 * @returns {{ workflows: Array<{ name: string, description: string }>, warnings: string[] }}
 */
function resolveWorkflows(agentDir, manifest) {
  const allItems = manifest?.capabilities?.workflows?.items || [];
  const items = allItems.slice(0, MAX_WORKFLOW_ITEMS);
  const workflows = [];
  const warnings = [];

  for (const item of items) {
    if (!item.name || !SAFE_COMMAND_NAME.test(item.name)) {
      warnings.push(`Skipped invalid workflow name: "${item.name}"`);
      continue;
    }

    let description = `Execute the ${item.name} workflow`;

    const workflowPath = safeResolveWorkflowPath(agentDir, item.file);
    if (!workflowPath) {
      warnings.push(`Invalid workflow file path: ${item.file}`);
    } else {
      try {
        const stat = fs.statSync(workflowPath);
        if (stat.size > MAX_WORKFLOW_FILE_SIZE) {
          warnings.push(`Workflow file too large, using fallback: ${item.file}`);
        } else {
          const content = fs.readFileSync(workflowPath, 'utf-8');
          const extracted = extractFrontmatterField(content, 'description');
          if (extracted) {
            description = extracted;
          }
        }
      } catch {
        warnings.push(`Could not read workflow file: ${item.file}`);
      }
    }

    workflows.push({ name: item.name, description });
  }

  return { workflows, warnings };
}

// ---------------------------------------------------------------------------
// IDE-specific adapters
// ---------------------------------------------------------------------------

/**
 * Generates Claude Code / Antigravity bridge files.
 * Format: YAML frontmatter with description.
 *
 * @param {Array<{ name: string, description: string }>} workflows
 * @returns {{ files: Array<{ path: string, content: string }> }}
 */
function generateClaudeCommands(workflows) {
  const files = workflows.map(({ name, description }) => ({
    path: `${CLAUDE_DIR}/${CLAUDE_COMMANDS_DIR}/${name}.md`,
    content: [
      BRIDGE_HEADER,
      '---',
      `description: "${sanitizeForYaml(description)}"`,
      '---',
      '',
      `Execute the /${name} workflow from the Devran AI Kit.`,
      '',
      `Read and follow the full instructions in .agent/workflows/${name}.md.`,
      '',
      'User request: ',
      '',
    ].join('\n'),
  }));

  return Object.freeze({ files: Object.freeze(files) });
}

/**
 * Generates Cursor IDE bridge files.
 * Format: Plain markdown (no frontmatter — Cursor commands use plain markdown).
 *
 * @param {Array<{ name: string, description: string }>} workflows
 * @returns {{ files: Array<{ path: string, content: string }> }}
 */
function generateCursorCommands(workflows) {
  const files = workflows.map(({ name, description }) => ({
    path: `${CURSOR_DIR}/${CURSOR_COMMANDS_DIR}/${name}.md`,
    content: [
      BRIDGE_HEADER,
      `# /${name}`,
      '',
      sanitizeForMarkdown(description),
      '',
      `Read and follow the full instructions in \`.agent/workflows/${name}.md\`.`,
      '',
      'User request: ',
      '',
    ].join('\n'),
  }));

  return Object.freeze({ files: Object.freeze(files) });
}

/**
 * Generates OpenCode IDE bridge files.
 * Format: YAML frontmatter with description + $ARGUMENTS template variable.
 *
 * @param {Array<{ name: string, description: string }>} workflows
 * @returns {{ files: Array<{ path: string, content: string }> }}
 */
function generateOpenCodeCommands(workflows) {
  const files = workflows.map(({ name, description }) => ({
    path: `${OPENCODE_DIR}/${OPENCODE_COMMANDS_DIR}/${name}.md`,
    content: [
      BRIDGE_HEADER,
      '---',
      `description: "${sanitizeForYaml(description)}"`,
      '---',
      '',
      `Execute the /${name} workflow from the Devran AI Kit.`,
      '',
      `Read and follow the full instructions in .agent/workflows/${name}.md.`,
      '',
      '$ARGUMENTS',
      '',
    ].join('\n'),
  }));

  return Object.freeze({ files: Object.freeze(files) });
}

/**
 * Generates VS Code Copilot prompt files (explicit opt-in only).
 * Format: YAML frontmatter with description + mode: "agent".
 * Extension: .prompt.md (VS Code requirement).
 *
 * NOTE: The provenance header is placed AFTER the YAML frontmatter block
 * (not before it like other adapters) because VS Code Copilot requires
 * the YAML frontmatter to be the very first content in the file.
 * The header is still within the first 128 bytes, so isKitGeneratedFile()
 * can detect it for provenance checks.
 *
 * @param {Array<{ name: string, description: string }>} workflows
 * @returns {{ files: Array<{ path: string, content: string }> }}
 */
function generateVSCodePrompts(workflows) {
  const files = workflows.map(({ name, description }) => ({
    path: `${GITHUB_PROMPTS_DIR}/${name}.prompt.md`,
    content: [
      '---',
      `description: "${sanitizeForYaml(description)}"`,
      'mode: "agent"',
      '---',
      BRIDGE_HEADER,
      '',
      `Execute the /${name} workflow from the Devran AI Kit.`,
      '',
      `Read and follow the full instructions in .agent/workflows/${name}.md.`,
      '',
      'User request: ',
      '',
    ].join('\n'),
  }));

  return Object.freeze({ files: Object.freeze(files) });
}

/**
 * Generates Windsurf IDE workflow bridge files.
 * Format: Plain markdown with title + numbered steps (no frontmatter).
 *
 * @param {Array<{ name: string, description: string }>} workflows
 * @returns {{ files: Array<{ path: string, content: string }> }}
 */
function generateWindsurfWorkflows(workflows) {
  const files = workflows.map(({ name, description }) => ({
    path: `${WINDSURF_DIR}/${WINDSURF_WORKFLOWS_DIR}/${name}.md`,
    content: [
      BRIDGE_HEADER,
      `# /${name}`,
      '',
      sanitizeForMarkdown(description),
      '',
      '## Steps',
      '',
      `1. Read and follow the full instructions in \`.agent/workflows/${name}.md\``,
      '2. Execute the workflow according to its defined steps and governance rules',
      '',
    ].join('\n'),
  }));

  return Object.freeze({ files: Object.freeze(files) });
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

/** @type {Record<string, (workflows: Array) => { files: Array }>} */
const IDE_ADAPTERS = Object.freeze({
  claude: generateClaudeCommands,
  cursor: generateCursorCommands,
  opencode: generateOpenCodeCommands,
  vscode: generateVSCodePrompts,
  windsurf: generateWindsurfWorkflows,
});

/**
 * Generates command bridge files for all detected (or specified) IDEs.
 *
 * @param {string} agentDir - Absolute path to .agent/ directory
 * @param {object} manifest - Parsed manifest.json
 * @param {object} [options={}]
 * @param {string} [options.ide] - Comma-separated IDE list or 'all'
 * @param {string} [options.projectRoot] - Project root for IDE auto-detection
 * @returns {{ [ide: string]: { files: Array }, warnings: string[], detectedIDEs: string[] }}
 */
function generateCommandBridges(agentDir, manifest, options = {}) {
  const { workflows, warnings } = resolveWorkflows(agentDir, manifest);

  let ides;
  if (options.ide === 'all') {
    ides = Object.keys(IDE_ADAPTERS);
  } else if (options.ide) {
    ides = options.ide.split(',').map(s => s.trim()).filter(s => IDE_ADAPTERS[s]);
  } else {
    ides = detectIDEs(options.projectRoot || path.dirname(agentDir));
  }

  const result = {};
  for (const ide of ides) {
    result[ide] = IDE_ADAPTERS[ide](workflows);
  }

  return Object.freeze({
    ...result,
    warnings: Object.freeze(warnings),
    detectedIDEs: Object.freeze([...ides]),
  });
}

module.exports = Object.freeze({
  extractFrontmatterField,
  sanitizeForYaml,
  sanitizeForMarkdown,
  safeResolveWorkflowPath,
  isKitGeneratedFile,
  detectIDEs,
  resolveWorkflows,
  generateClaudeCommands,
  generateCursorCommands,
  generateOpenCodeCommands,
  generateVSCodePrompts,
  generateWindsurfWorkflows,
  generateCommandBridges,
  IDE_ADAPTERS,
});
